[창현] Misstion 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/29-westagram-backend-4-team pull request #11
Opened 2022-01-17 07:40 UTC by cch0807

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
회원가입 비밀번호 암호화 적용
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
패스워드를 bcrypt로 암호화.
암호화된 패스워드를 decode해서 문자열 타입으로 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
그냥 bcrypt로 암호화된 패스워드를 반환하면 암호화된 데이터 타입이 bytes타입이라
decode를 해서 문자열로 바꿔줘야 한다고 생각해서 이렇게 했습니다!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-17 08:07 UTC, newdana01 commented
혹싀 requirements.txt에 bcrypt 추가 하셨나요??

2022-01-17 08:09 UTC, cch0807 commented
앗 수정하겠습니다!

2022-01-17 08:25 UTC, newdana01 commented
구웃

2022-01-17 08:34 UTC, bigfanoftim requested changes

2022-01-17 08:34 UTC, bigfanoftim commented on students/changhyeon/users/views.py
> +      hashed_password = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt())
`create` 부분이 아닌 해쉬된 패스워드를 만드는 곳에서부터 처리를 마무리하고 `create`를 해주는 것이 더 좋을 것 같아요 창현님!
```suggestion
      hashed_password = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode('utf-8')
```

2022-01-17 08:34 UTC, bigfanoftim commented on students/changhyeon/users/views.py
> +        password     = hashed_password.decode('utf-8'),
```suggestion
        password     = hashed_password,
```

2022-01-17 08:34 UTC, bigfanoftim commented on students/changhyeon/users/views.py
> +import json,bcrypt
불필요한 import문은 지워주시고, import문 순서를 잘 지켜서 만들어주세요.
위와 같은 순서대로 import 하는 모듈을 정렬해주시고, 파이썬과 장고, 장고와 내가 만든 클래스들 사이에 한 줄씩 띄워주세요.

(python convention 문서 참고해주세요.)

```python
# 파이썬 built-in 모듈
import json, re

# 외부 모듈
from django.http      import JsonResponse
from django.views     import View

# 내가 만든 사용자 모듈
from users.models     import User
```

2022-01-17 08:45 UTC, cch0807 commented on students/changhyeon/users/views.py
> +      hashed_password = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt())
확인하였습니다!

2022-01-17 08:45 UTC, cch0807 commented on students/changhyeon/users/views.py
> +        password     = hashed_password.decode('utf-8'),
확인하였습니다!

2022-01-17 08:45 UTC, cch0807 commented on students/changhyeon/users/views.py
> +import json,bcrypt
확인하였습니다!

2022-01-18 01:31 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-01-18 01:31 UTC, merged