[이혜린] Mission 2: 모델링
wecode-bootcamp-korea/29-westagram-backend-4-team pull request #6
Opened 2022-01-13 08:03 UTC by lindsey26

## 수정 사항 간략한 한줄 요약
[Mission 2] 모델링
		 
## 수정 사항들 자세한 내용
1. User Branch 생성
2. User App 생성
3. User 테이블 생성
4. Pull Request

## 기타 질문 및 특이 사항
[Django] C.R.U.D 1 -> Model 작성하기 에서 배웠던 과정을 보면서
<1-1. models.py 작성>에 해당하는 과제를 완료하였고,
<1-2. models.py 작성 내용 DB에 적용> 과정과
<1-3. Mysql server(Database)에 잘 적용되었는지 확인> 과정은 이번 과제 지시사항에는 없는 것 같아 생략했는데, 이 두 과정도 다 해서 올려야 하는 건가요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-13 08:16 UTC, lordmyshepherd requested changes

2022-01-13 08:16 UTC, lordmyshepherd commented on students/hyerin/westagram/users/models.py
> +    p_number = models.CharField(max_length=50)
몇 가지 수정이 필요해 보여요~
1. class 내에 member 변수 선언시 빈 줄 삭제
2.`p_number` -> `phone_number` (변수명 줄여쓰지 않기, 파이썬 컨벤션 자료를 참고해주세요~)
3. 사용자 중복 저장을 피하기 위해서 unique 속성 추가
4. 이력 관리용 컬럼 추가 필요

```suggestion
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=50)
```

2022-01-13 08:16 UTC, lordmyshepherd commented on students/hyerin/westagram/users/models.py
> +
데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.

```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)
```

2022-01-13 08:16 UTC, lordmyshepherd commented on students/hyerin/westagram/users/models.py
> +    password = models.CharField(max_length=50)
password property는 나중에 해시(암호화)된 비밀번호 길이를 고려해서 넉넉하게 200 이상으로 설정해주세요.

2022-01-13 08:16 UTC, lordmyshepherd commented on students/hyerin/westagram/users/models.py
> +    email = models.CharField(max_length=50)
email field에 unique 속성을 추가하셔서 유저가 중복 저장되는 문제가 발생하지 않도록 수정해주세요!

2022-01-17 05:11 UTC, bigfanoftim requested changes

2022-01-17 05:11 UTC, bigfanoftim commented on students/hyerin/westagram/users/models.py
> +    updated_at = models.DateTimeField(auto_now=True)
가독성을 위해 `=` 혹은 `:`를 기준으로 정렬해주세요!

```python
name     = models.CharField(...)
email    = models.CharField(...)
password = models.CharField(...)
```

2022-01-17 05:18 UTC, lindsey26 commented on students/hyerin/westagram/users/models.py
> +    updated_at = models.DateTimeField(auto_now=True)
완료 하였습니다!

2022-01-17 05:27 UTC, bigfanoftim approved these changes

2022-01-17 05:28 UTC, merged