[다희 Mission 3: views.py 작성 및 url 패턴 맵핑
wecode-bootcamp-korea/29-westagram-backend-4-team pull request #8
Opened 2022-01-14 07:02 UTC by newdana01

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- users.views 내 post() 구현
- urlpatterns 맵핑

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-14 07:39 UTC, lordmyshepherd requested changes

2022-01-14 07:39 UTC, lordmyshepherd commented on students/dahee/users/views.py
> +            phone_number_validation = re.compile(r'\d{3}-\d{3,4}-\d{4}')
정규표현식을 사용할 경우, 자주 사용되는 경우가 아니라면 `compile()`해서 사용하지 않고, `match()`를 사용하는 것을 공식 문서에서 추천하고 있습니다.

```python
REGEX_EMAIL    = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
REGEX_PASSWORD = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'

    if not re.match(REGEX_EMAIL, value):
        ...
    if not re.match(REGEX_PASSWORD, value):
        ...
```

2022-01-14 07:39 UTC, lordmyshepherd commented on students/dahee/users/views.py
> +            phone_number_validation = re.compile(r'\d{3}-\d{3,4}-\d{4}')
아래 line 26~31 코드와 합쳐볼 수 있겠습니다~~

2022-01-14 07:39 UTC, lordmyshepherd commented on students/dahee/users/views.py
> +            )
User 인스턴스를 만드는 코드가 line 22~31 이후로 옮겨지는게 가독성과 효율 측면에서 좋을 것 같습니다.

지금 코드는 인스턴스를 만들었는데 이후에 input data의 유효성을 검사하는 부분에서 에러가 발생할 경우, 불필요하게 객체를 생성해버린 상황이될 수 있기 때문입니다.

2022-01-14 07:39 UTC, lordmyshepherd commented on students/dahee/users/views.py
> +            return JsonResponse({"message": "SUCCESS"}, status=201)
return문을 else 보다는 try 문 안으로 넣어주시는게 좋을 것 같습니다.

2022-01-14 07:52 UTC, newdana01 commented on students/dahee/users/views.py
> +            )
수정 하였습니다 😸

2022-01-14 07:52 UTC, newdana01 commented on students/dahee/users/views.py
> +            return JsonResponse({"message": "SUCCESS"}, status=201)
수정 하였습니다 😸

2022-01-14 07:53 UTC, newdana01 commented on students/dahee/users/views.py
> +            phone_number_validation = re.compile(r'\d{3}-\d{3,4}-\d{4}')
수정 하였습니다 😸

2022-01-14 08:02 UTC, bigfanoftim requested changes

2022-01-14 08:02 UTC, bigfanoftim commented on students/dahee/users/urls.py
> +    path('/sign_up', SignUpView.as_view()),
![image](https://user-images.githubusercontent.com/62135254/149469624-4e4b750a-862d-4d5f-a2b6-38126f587515.png)
우선 `urls.py` 를 작성하실 때에는 공식문서와 같이 `_`가 아닌 `-`를 활용해주세요~
추가로 `sign up`의 경우 간단하게 `signup`이라고 작성하는게 더 좋을 것 같습니다.

2022-01-14 08:02 UTC, bigfanoftim commented on students/dahee/users/views.py
> +from django.views import View
```suggestion
from django.db    import IntegrityError
from django.http  import JsonResponse
from django.views import View
```

2022-01-14 08:02 UTC, bigfanoftim commented on students/dahee/users/views.py
> +                phone_number = user_data["phone_number"]
가독성을 위해 `=` 혹은 `:`를 기준으로 정렬해주세요!

```python
name     = models.CharField(...)
email    = models.CharField(...)
password = models.CharField(...)
```

2022-01-14 08:02 UTC, bigfanoftim commented on students/dahee/users/views.py
> +
반복적으로 활용되는 값들은 변수로 지정하여 재사용해주세요~

```python
email    = user_data['email']
password = user_data['password']
```

2022-01-14 08:02 UTC, bigfanoftim commented on students/dahee/users/views.py
> +                return JsonResponse({"message": "INVALID_EMAIL"}, status=400)
`search`가 아니라 `match`를 사용하는게 어떨까요? 차이를 한 번 구글링해서 파악해보신 후 수정해주세요 다희님~

2022-01-14 08:02 UTC, bigfanoftim commented on students/dahee/users/views.py
> +            )
`request body`로 건네받은 값들을 검증 하기 전에 미리 객체를 만들어 버리는 것은 불필요한 작업일 것 같습니다!
validation을 다 통과한 이후에 데이터를 만들어 주는게 어떨까요?

2022-01-14 08:02 UTC, bigfanoftim commented on students/dahee/users/views.py
> +            return JsonResponse({"message": "EMAIL_ALREADY_EXISTS"}, status=400)
예외처리 너무 좋습니다 다희님~ 혹시 이런식으로 처리하는 경우 PK 값이 밀리는 것도 확인하셨나요?
`unique=True` 옵션이 있기 때문에 DB 수준에서 검증을 할 수 도 있지만, 이 경우 데이터를 생성하다가 다시 삭제하는 불필요한 동작이 일어납니다. 
따라서 추가적으로 `filter()`, `exists()`를 활용하여 간단한 로직으로 미리 걸러주는 것도 좋아보입니다~

2022-01-16 07:35 UTC, newdana01 commented on students/dahee/users/views.py
> +            return JsonResponse({"message": "EMAIL_ALREADY_EXISTS"}, status=400)
수정하였습니다 😸

2022-01-16 07:35 UTC, newdana01 commented on students/dahee/users/views.py
> +            )
수정하였습니다 😸

2022-01-16 07:36 UTC, newdana01 commented on students/dahee/users/views.py
> +                return JsonResponse({"message": "INVALID_EMAIL"}, status=400)
수정하였습니다 😸

2022-01-16 07:36 UTC, newdana01 commented on students/dahee/users/views.py
> +
수정하였습니다 😸

2022-01-16 07:36 UTC, newdana01 commented on students/dahee/users/views.py
> +                phone_number = user_data["phone_number"]
수정하였습니다 😸

2022-01-16 07:36 UTC, newdana01 commented on students/dahee/users/views.py
> +from django.views import View
수정하였습니다 😸

2022-01-16 07:36 UTC, newdana01 commented on students/dahee/users/urls.py
> +    path('/sign_up', SignUpView.as_view()),
수정하였습니다 😸

2022-01-17 02:09 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-01-17 02:09 UTC, merged